name: od-fridge-items-mlflow-deploy
endpoint_name: od-fridge-items-endpoint
type: kubernetes
model: azureml:fridge-items-mlflow-model@latest
instance_type: gpumodel2
resources:
  requests:
    cpu: "0.1"
    memory: "0.1Gi"
  limits:
    cpu: "0.2"
    memory: "200Mi"