$schema: https://azuremlschemas.azureedge.net/latest/kubernetesOnlineDeployment.schema.json
name: blue
type: kubernetes
endpoint_name: od-fridge-items-endpoint
model: azureml:fridge-items-mlflow-model@latest
instance_type: gpumodel2
environment: 
  conda_file: ../../azureml-examples/cli/endpoints/online/model-1/environment/conda.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.3-cudnn8-ubuntu20.04:latest
request_settings:
  request_timeout_ms: 3000
  max_queue_wait_ms: 3000
tags:
  tag1: deployment-tag2-value
instance_count: 1
scale_settings:
  type: target_utilization
  min_instances: 1
  max_instances: 3
  polling_interval: 10
  target_utilization_percentage: 70
