# This is a basic workflow to help you get started with Actions

name: Provision and Configure Azure Infrastructure

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Infrastructure_Provisioning:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: write-all

    
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/azml-aks-online-endpoint/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      
      - name: Generate runner url from secret
        run: |
            export gh_runner_url="https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token"
            echo "GH_runner_url=$gh_runner_url" >> $GITHUB_ENV


      - name: Generate runner registration token 
        run: |
            export token="$(curl -L   -X POST   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.GH_PAT }} "  -H "X-GitHub-Api-Version: 2022-11-28" $GH_runner_url | jq -r .token)"
            echo "GH_runner_token=$token" >> $GITHUB_ENV
     

      # Run Terraform Apply with Auto Approve
      - name: Terraform Apply for Intial Terraform Config
        working-directory: /home/runner/work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Intial_Terraform

  